### PR TITLE
Fixed missing ARC reference bridge

### PR DESCRIPTION
**Pull request by bryanwayb**
Fixed ARC compile error when directly including `BFPaperButton.m` in a project

### CODE REVIEW

**Comment by bfeher** [comment]
Thank you :+1:

**Comment by bfeher** [comment]
Not sure what this solved actually, but now xcode is throwing an error:
screen shot 2016-02-25 at 8 51 17 am

I'm going to have to revert until this is cleared up. Sorry.

**Comment by bryanwayb** [comment]
Sorry about that. Huh, I'll need to check into this when I'm around my Mac.
Thanks for the screen cap.

I received a similar error when building by directly including the .m file
which prompted me to add the bridge cast.

**Comment by bfeher** [comment]
No problem. I know it might not be to your liking, but have you tried using it with CocoaPods?

**Comment by bryanwayb** [comment]
Actually yes I have. I choose git submodules for big projects though since
they allow for a bit more flexibility with structure and organizational
management. It's a pain sometimes, but alas I picked poison.

**Pull request merged**
